//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserPresentacion.ServiceUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenderUser {
            get {
                return this.GenderUserField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderUserField, value) != true)) {
                    this.GenderUserField = value;
                    this.RaisePropertyChanged("GenderUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((this.IdUserField.Equals(value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameUser {
            get {
                return this.NameUserField;
            }
            set {
                if ((object.ReferenceEquals(this.NameUserField, value) != true)) {
                    this.NameUserField = value;
                    this.RaisePropertyChanged("NameUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUser.IUserConsumer")]
    public interface IUserConsumer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/UpdateUser", ReplyAction="http://tempuri.org/IUserConsumer/UpdateUserResponse")]
        bool UpdateUser(string name, string gender, System.DateTime birthdate, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/UpdateUser", ReplyAction="http://tempuri.org/IUserConsumer/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(string name, string gender, System.DateTime birthdate, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/CreateUser", ReplyAction="http://tempuri.org/IUserConsumer/CreateUserResponse")]
        bool CreateUser(string name, string gender, System.DateTime birthdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/CreateUser", ReplyAction="http://tempuri.org/IUserConsumer/CreateUserResponse")]
        System.Threading.Tasks.Task<bool> CreateUserAsync(string name, string gender, System.DateTime birthdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/SearchUser", ReplyAction="http://tempuri.org/IUserConsumer/SearchUserResponse")]
        UserPresentacion.ServiceUser.User[] SearchUser(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/SearchUser", ReplyAction="http://tempuri.org/IUserConsumer/SearchUserResponse")]
        System.Threading.Tasks.Task<UserPresentacion.ServiceUser.User[]> SearchUserAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/ReadUsers", ReplyAction="http://tempuri.org/IUserConsumer/ReadUsersResponse")]
        UserPresentacion.ServiceUser.User[] ReadUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/ReadUsers", ReplyAction="http://tempuri.org/IUserConsumer/ReadUsersResponse")]
        System.Threading.Tasks.Task<UserPresentacion.ServiceUser.User[]> ReadUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/DeleteUser", ReplyAction="http://tempuri.org/IUserConsumer/DeleteUserResponse")]
        bool DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserConsumer/DeleteUser", ReplyAction="http://tempuri.org/IUserConsumer/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserConsumerChannel : UserPresentacion.ServiceUser.IUserConsumer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserConsumerClient : System.ServiceModel.ClientBase<UserPresentacion.ServiceUser.IUserConsumer>, UserPresentacion.ServiceUser.IUserConsumer {
        
        public UserConsumerClient() {
        }
        
        public UserConsumerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserConsumerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserConsumerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserConsumerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateUser(string name, string gender, System.DateTime birthdate, int id) {
            return base.Channel.UpdateUser(name, gender, birthdate, id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(string name, string gender, System.DateTime birthdate, int id) {
            return base.Channel.UpdateUserAsync(name, gender, birthdate, id);
        }
        
        public bool CreateUser(string name, string gender, System.DateTime birthdate) {
            return base.Channel.CreateUser(name, gender, birthdate);
        }
        
        public System.Threading.Tasks.Task<bool> CreateUserAsync(string name, string gender, System.DateTime birthdate) {
            return base.Channel.CreateUserAsync(name, gender, birthdate);
        }
        
        public UserPresentacion.ServiceUser.User[] SearchUser(string name) {
            return base.Channel.SearchUser(name);
        }
        
        public System.Threading.Tasks.Task<UserPresentacion.ServiceUser.User[]> SearchUserAsync(string name) {
            return base.Channel.SearchUserAsync(name);
        }
        
        public UserPresentacion.ServiceUser.User[] ReadUsers() {
            return base.Channel.ReadUsers();
        }
        
        public System.Threading.Tasks.Task<UserPresentacion.ServiceUser.User[]> ReadUsersAsync() {
            return base.Channel.ReadUsersAsync();
        }
        
        public bool DeleteUser(int id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
    }
}
